# Sistemas Inteligentes

## Laboratório 3 - Redução de Dimensionalidade e Regressão

Algoritmos de Redução de dimensionalidade:
- Principal Component Analysis (PCA)
- Independent Component Analysis (ICA)
- Isometric Mapping (Isomap)
- T-Distributed Stochastic Neighbor Embedding (TSNE)

Modelos de regressão linear:
- Least Squares
- Ridge
- Lasso
- Lasso Least-angle regression (LARS)
- RANdom SAmple Consensus (RANSAC)
- Theil-Sen

### Identificação do Aluno

#### Nome Completo

ESCREVA AQUI A SUA RESPOSTA

#### RA

ESCREVA AQUI A SUA RESPOSTA

## Importação e preparação dos dados

Importe o dataset de pacientes diabéticos da biblioteca Scikit (load_diabetes) e separe os dados entre atributos (X) e saídas (y).

In [6]:
from sklearn.datasets import load_diabetes
import numpy as np

X, y = load_diabetes(return_X_y=True)

Mostre os formatos da variável de atributos e da variável de saídas.

In [11]:
print(X)
print(len(X))
print(X.ndim)

[[ 0.03807591  0.05068012  0.06169621 ... -0.00259226  0.01990842
  -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 ... -0.03949338 -0.06832974
  -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 ... -0.00259226  0.00286377
  -0.02593034]
 ...
 [ 0.04170844  0.05068012 -0.01590626 ... -0.01107952 -0.04687948
   0.01549073]
 [-0.04547248 -0.04464164  0.03906215 ...  0.02655962  0.04452837
  -0.02593034]
 [-0.04547248 -0.04464164 -0.0730303  ... -0.03949338 -0.00421986
   0.00306441]]
442
2


In [9]:
print(y)
print(len(y))
print(y.ndim)

[151.  75. 141. 206. 135.  97. 138.  63. 110. 310. 101.  69. 179. 185.
 118. 171. 166. 144.  97. 168.  68.  49.  68. 245. 184. 202. 137.  85.
 131. 283. 129.  59. 341.  87.  65. 102. 265. 276. 252.  90. 100.  55.
  61.  92. 259.  53. 190. 142.  75. 142. 155. 225.  59. 104. 182. 128.
  52.  37. 170. 170.  61. 144.  52. 128.  71. 163. 150.  97. 160. 178.
  48. 270. 202. 111.  85.  42. 170. 200. 252. 113. 143.  51.  52. 210.
  65. 141.  55. 134.  42. 111.  98. 164.  48.  96.  90. 162. 150. 279.
  92.  83. 128. 102. 302. 198.  95.  53. 134. 144. 232.  81. 104.  59.
 246. 297. 258. 229. 275. 281. 179. 200. 200. 173. 180.  84. 121. 161.
  99. 109. 115. 268. 274. 158. 107.  83. 103. 272.  85. 280. 336. 281.
 118. 317. 235.  60. 174. 259. 178. 128.  96. 126. 288.  88. 292.  71.
 197. 186.  25.  84.  96. 195.  53. 217. 172. 131. 214.  59.  70. 220.
 268. 152.  47.  74. 295. 101. 151. 127. 237. 225.  81. 151. 107.  64.
 138. 185. 265. 101. 137. 143. 141.  79. 292. 178.  91. 116.  86. 122.
  72. 

## Redução de Dimensionalidade

Importe e aplique as funções de redução de dimensionalidade (PCA, FastICA, Isomap e TSNE) para reduzir a dimensionalidade a apenas uma feature.

In [12]:
from sklearn.decomposition import PCA
from sklearn.decomposition import FastICA
from sklearn.manifold import Isomap
from sklearn.manifold import TSNE

Mostre o formato da nova variável de atributos após a redução de dimensionalidade para cada algoritmo.

In [28]:
pca = PCA(n_components=1)
Xpca = pca.fit_transform(X)
print(Xpca)
print(len(Xpca))
print(Xpca.ndim)

[[ 2.79306207e-02]
 [-1.34686052e-01]
 [ 1.29447396e-02]
 [ 2.34543980e-03]
 [-3.59806910e-02]
 [-1.88660280e-01]
 [-9.48347610e-02]
 [ 9.87389258e-02]
 [ 2.86833351e-02]
 [-1.00910711e-02]
 [-1.83419418e-01]
 [ 1.88796730e-02]
 [-7.59323171e-02]
 [ 1.51473512e-02]
 [-8.01694940e-02]
 [ 1.40488092e-01]
 [ 7.58600302e-03]
 [ 1.08839198e-01]
 [-5.49947993e-02]
 [-8.42651351e-02]
 [-9.55955468e-02]
 [-9.18719735e-02]
 [-7.97268029e-02]
 [ 1.79486384e-01]
 [-6.13394313e-02]
 [ 3.92363820e-03]
 [-1.84828537e-01]
 [-4.96967732e-02]
 [-8.36788209e-02]
 [-1.71885595e-02]
 [-5.58611904e-02]
 [-1.64968530e-01]
 [ 1.24056068e-01]
 [-1.36513766e-01]
 [-1.40162432e-01]
 [-3.34396746e-02]
 [-6.77447975e-03]
 [-6.69444076e-02]
 [ 1.85191456e-01]
 [ 7.28741657e-03]
 [ 1.15507838e-01]
 [-1.74462889e-01]
 [-2.76506311e-02]
 [-8.56914170e-02]
 [ 9.67999958e-02]
 [-1.01473230e-02]
 [-1.15570589e-01]
 [-1.61765051e-01]
 [-4.07025090e-02]
 [ 6.12607134e-02]
 [-4.92354907e-02]
 [ 9.78432196e-03]
 [-1.4618861

In [31]:
ica = FastICA(n_components=1)
Xica = ica.fit_transform(X)
print(Xica)
print(len(Xica))
print(Xica.ndim)

[[-1.39232315e-02]
 [ 6.71401150e-02]
 [-6.45286793e-03]
 [-1.16918638e-03]
 [ 1.79361388e-02]
 [ 9.40459138e-02]
 [ 4.72745073e-02]
 [-4.92207078e-02]
 [-1.42984547e-02]
 [ 5.03033287e-03]
 [ 9.14333784e-02]
 [-9.41139335e-03]
 [ 3.78517628e-02]
 [-7.55085538e-03]
 [ 3.99639677e-02]
 [-7.00323940e-02]
 [-3.78157282e-03]
 [-5.42556271e-02]
 [ 2.74145473e-02]
 [ 4.20056180e-02]
 [ 4.76537540e-02]
 [ 4.57975771e-02]
 [ 3.97432891e-02]
 [-8.94727870e-02]
 [ 3.05773048e-02]
 [-1.95590795e-03]
 [ 9.21358154e-02]
 [ 2.47735160e-02]
 [ 4.17133442e-02]
 [ 8.56838431e-03]
 [ 2.78464375e-02]
 [ 8.22357316e-02]
 [-6.18411375e-02]
 [ 6.80512183e-02]
 [ 6.98700546e-02]
 [ 1.66694588e-02]
 [ 3.37703379e-03]
 [ 3.33713487e-02]
 [-9.23167281e-02]
 [-3.63272943e-03]
 [-5.75799007e-02]
 [ 8.69686075e-02]
 [ 1.37836585e-02]
 [ 4.27166101e-02]
 [-4.82541639e-02]
 [ 5.05837408e-03]
 [ 5.76111819e-02]
 [ 8.06388186e-02]
 [ 2.02899342e-02]
 [-3.05380644e-02]
 [ 2.45435697e-02]
 [-4.87742041e-03]
 [ 7.2874067

In [30]:
isomap = Isomap(n_components=1)
Xiso = isomap.fit_transform(X)
print(Xiso)
print(len(Xiso))
print(Xiso.ndim)

[[-0.28172333]
 [ 0.23516854]
 [-0.2553752 ]
 [ 0.18186422]
 [ 0.23349804]
 [ 0.39670369]
 [-0.10843973]
 [-0.23441199]
 [-0.26508133]
 [ 0.1191197 ]
 [ 0.36118194]
 [-0.13856479]
 [ 0.22785759]
 [-0.18484931]
 [ 0.16265048]
 [-0.36021715]
 [ 0.10240097]
 [-0.32197466]
 [ 0.18625698]
 [ 0.22686596]
 [ 0.2167407 ]
 [-0.13484277]
 [ 0.29547055]
 [-0.38848749]
 [ 0.21487362]
 [-0.23993709]
 [ 0.34544959]
 [ 0.24218114]
 [ 0.31977707]
 [-0.05253844]
 [ 0.24410414]
 [ 0.29634585]
 [-0.31714725]
 [ 0.36968361]
 [ 0.3278626 ]
 [ 0.03436196]
 [ 0.09399672]
 [ 0.28144008]
 [-0.36781663]
 [-0.21931274]
 [-0.24726455]
 [ 0.29416741]
 [-0.25199647]
 [ 0.19296826]
 [-0.28709149]
 [-0.16542531]
 [ 0.30559272]
 [ 0.35715476]
 [-0.11782382]
 [-0.24760714]
 [ 0.28447848]
 [-0.2441819 ]
 [ 0.28206963]
 [ 0.23781766]
 [ 0.26042101]
 [ 0.22007022]
 [ 0.12824993]
 [ 0.38127053]
 [ 0.26988863]
 [-0.25438935]
 [ 0.34520493]
 [-0.28063116]
 [-0.08864443]
 [ 0.24317992]
 [-0.22597785]
 [-0.25467585]
 [-0.26592

In [32]:
tsne = TSNE(n_components=1)
Xtsne = tsne.fit_transform(X)
print(Xtsne)
print(len(Xtsne))
print(Xtsne.ndim)

[[  8.340905  ]
 [-12.564726  ]
 [  8.019125  ]
 [ -7.6080756 ]
 [-10.242363  ]
 [-16.453176  ]
 [ -4.751145  ]
 [ 13.229688  ]
 [  7.7035103 ]
 [  0.7066277 ]
 [-17.09711   ]
 [  6.8594556 ]
 [-11.339183  ]
 [  9.583068  ]
 [-11.614881  ]
 [ 14.45099   ]
 [ -0.38147807]
 [ 13.616432  ]
 [ -8.528009  ]
 [-10.654283  ]
 [-15.89954   ]
 [ -4.6750026 ]
 [ -9.619567  ]
 [ 17.577772  ]
 [ -8.760767  ]
 [  9.6843405 ]
 [-16.941765  ]
 [ -9.031548  ]
 [-13.99509   ]
 [ -1.6328385 ]
 [ -9.234619  ]
 [-14.80484   ]
 [ 16.286392  ]
 [-13.274193  ]
 [-14.7969055 ]
 [ -6.450708  ]
 [ -0.21404019]
 [ -9.8074    ]
 [ 15.281114  ]
 [  7.708238  ]
 [ 12.446859  ]
 [-16.542347  ]
 [  9.51321   ]
 [-12.530853  ]
 [ 15.989163  ]
 [  7.544767  ]
 [-15.978187  ]
 [-16.634575  ]
 [ -2.0640798 ]
 [  9.930618  ]
 [-10.365577  ]
 [  8.175502  ]
 [ -9.944916  ]
 [ -0.4276769 ]
 [ -9.878957  ]
 [-12.405249  ]
 [  0.7054895 ]
 [-15.726559  ]
 [-12.747692  ]
 [ 12.678765  ]
 [-16.54073   ]
 [  9.781512  ]
 [ -3.95

### Caso mais simples

Faça a separação dos dados para treinamento e teste. Reserve 20% dos dados para teste.

In [9]:
### Escreva seu código aqui ###

Importe o regressor linear e utilize-o para gerar um modelo, então faça uma regressão com os dados de teste.

In [10]:
### Escreva seu código aqui ###

Importe as funções de erro quadrático médio (MSE) e o coeficiente de determinação (R²), então imprima o MSE e o R².

In [11]:
### Escreva seu código aqui ###

Então exiba o gráfico de dispersão dos dados de teste e a curva de regressão gerada.

In [12]:
### Escreva seu código aqui ###

### Comparando Métodos de Redução de Dimensionalidade

Agora, a fim de comparar com outras técnicas, crie um método iterativo que realize as etapas de separação dos dados entre treinamento e teste, gere um modelo de regressão linear, faça a predição com base nos dados de testes e calcule o erro quadrático médio e o coeficiente de determinação para cada iteração. Então, calcule os valores mínimo, médio, máximo e desvio padrão para cada uma dessas duas métricas. Por fim, plote os histogramas (com 100 bins) das duas métricas. Use 10000 (dez mil) iterações.

#### PCA

In [13]:
### Escreva seu código aqui ###

#### ICA

In [14]:
### Escreva seu código aqui ###

#### Isomap

In [15]:
### Escreva seu código aqui ###

#### TSNE

In [16]:
### Escreva seu código aqui ###

### Comparando modelos de Regressão

Exiba o gráfico de dispersão dos dados de teste e a curva de regressão gerada em cada caso.

#### Least Squares

In [17]:
### Escreva seu código aqui ###

#### Ridge

In [18]:
### Escreva seu código aqui ###

#### Lasso

In [19]:
### Escreva seu código aqui ###

#### Lasso LARS

In [20]:
### Escreva seu código aqui ###

#### Bayesian Ridge

In [21]:
### Escreva seu código aqui ###

#### RANSAC

In [22]:
### Escreva seu código aqui ###

#### Theil-Sen

In [23]:
### Escreva seu código aqui ###

### Gráfico geral comparativo

Em uma mesma figura, plote novamente o gráfico de dispersão e mais cada uma das curvas geradas utilizando cada técnica deste laboratório. Atente-se a fazer com que o gráfico seja suficientemente autoexplicativo, então utilize diferentes cores, insira uma legenda etc.

In [24]:
### Escreva seu código aqui ###